### ISSUE TITLE
No output of any sort when starting the bot

### ISSUE THREAD

**Issue by MarcoFederici1999** [ingobeans/Auto-OWL-Watcher#1]
I tried setting up the bot, I added both the Discord webhook URL and the Youtube API key but when I try to run it I'm met with this error:
```
Traceback (most recent call last):
  File "C:\Users\Marco\Desktop\main.py", line 1, in <module>
    import google.auth
ModuleNotFoundError: No module named 'google.auth'
```
I then installed all the google libraries needed for the bot to start, such as 'google-api-python-client' and 'selenium'.
After doing it, the bot managed to start, but nothing appears on screen to tell if it's actually working or not:
![Screenshot_1](https://user-images.githubusercontent.com/13008862/235106391-ce6c7315-6e19-4344-bda4-7298dfce27dc.png)

**Comment by ingobeans** [comment]
You can set discord_webhook_logging to False
(Line 15). This outputs to console rather than through discord.

I recommend turning up logging level to 4, for more frequent logging

**Comment by MarcoFederici1999** [comment]
Ok, it looks like that was a mistake on my end, I turned up the logging level and switched over to console logging and now it reports even when there's no livestream, so it works properly.
