### ISSUE TITLE
OWL is streaming but the program status is still "Auto OWL is currently not streaming."

### ISSUE THREAD

**Issue by moltyhero** [ingobeans/Auto-OWL-Watcher#12]

**Comment by moltyhero** [comment]
Update - after some time (about 15 minutes), it started watching, so it seem to be a bit inconsistent

**Comment by ingobeans** [comment]
It only checks for streams every 15 minutes, so there's usually a bit of downtime between streams.

Thanks for trying out the new version btw! LMK if you find any other issues!
