### ISSUE TITLE
How Would I use it?

### ISSUE THREAD

**Issue by LowHighh** [ingobeans/Auto-OWL-Watcher#2]
Would you be kind enough to make a video guide?

**Comment by moltyhero** [comment]
Additionally to the steps in the readme, you need to install Python, add it to PATH and then
pip install google-api-python-client
pip install google-auth
pip install requests
pip install selenium
After that run launch headless.vbs

**Comment by ingobeans** [comment]
> Additionally to the steps in the readme, you need to install Python, add it to PATH and then pip install google-api-python-client pip install google-auth pip install requests pip install selenium After that run launch headless.vbs

I updated readme.md with these new instructions
