### ISSUE TITLE
API request quota

### ISSUE THREAD

**Issue by heretolurk** [ingobeans/Auto-OWL-Watcher#4]
Currently the script uses a search request on youtube that uses 100 units of quota from the API. Without special approval from youtube the default is set to 10000. A day with no streams would use 21600 units and a day with 24 hours of streams would use 14400 quota units. Is it possible to adjust the code to not pass the 10K limit? 

One possible suggestion would be to very occasionally search (100 units) upcoming instead of live, and of the video ids listed in that result use the list (1 unit) command for those videos and check the liveStreamingDetails part. I'm not super familiar with coding or I would suggest actual code but I do love your script.

**Comment by ingobeans** [comment]
I've currently just issued a hotfix, to up reload delays to 15 minutes, which should only use 9600 points per 24 hours. This is still a poor way of doing it, but for the moment it should be fine.

I've looked in to what you suggested and it seems like a good solution, and something I'll likely implement in the future (if I continue this project).

**Comment by heretolurk** [comment]
Much appreciated
