### ISSUE TITLE
HttpError 403

### ISSUE THREAD

**Issue by Chekhov1337** [ingobeans/Auto-OWL-Watcher#6]
![image](https://user-images.githubusercontent.com/52062914/235376420-e3ac004c-4252-43b9-85fc-7645d102c3d2.png)
Hi. Have some strange issue

**Comment by Chekhov1337** [comment]
On some streams script works fine, on some I get this error

**Comment by heretolurk** [comment]
That is the error for api quota exceeded mentioned in issue 4. If you get the updated code it should correct this for the most part but you will have to wait until the quota resets at 12AM PST. You can see your quota usage on the google developer console where you got your api.

**Comment by ingobeans** [comment]
As heretolurk stated, this means you have exceeded your YouTube API quota.
The new versions of the script should no longer get this problem. 
Quota resets daily and if you want to reset it manually you can simply make a new project over at google developer console, and get a new API key.
